### ISSUE TITLE
JedisConnectionException during shutdown on Velocity

### ISSUE THREAD

**Issue by tmantti** [A248/ExecuteEverywhereReloaded#2]
Velocity 1.1.3
ExecuteEverywhereReloaded 0.1.2
Plugins: Advanced-Portals-0.5.12, AdvancedBan-Velocity-2.3.0, executeeverywhere-0.1.2, LuckPerms-Velocity-5.2.106, ServerListPlus-3.5.0-Velocity, ViaVersion-3.2.1

```
[09:59:02 ERROR]: Some errors occurred whilst posting event ProxyShutdownEvent.
[09:59:02 ERROR]: #1: 

space.arim.executeeverywhere.shaded.jedis.jedis.exceptions.JedisConnectionException: JedisPubSub is not subscribed to a Jedis instance.
        at space.arim.executeeverywhere.shaded.jedis.jedis.JedisPubSub.unsubscribe(JedisPubSub.java:48) ~[?:?]
        at space.arim.executeeverywhere.ExecuteEverywhere.close(ExecuteEverywhere.java:72) ~[?:?]
        at space.arim.executeeverywhere.velocity.ExecuteEverywhereVelocity.onShutdown(ExecuteEverywhereVelocity.java:61) ~[?:?]
        at net.kyori.event.asm.generated.d723402a16.ExecuteEverywhereVelocity-onShutdown-ProxyShutdownEvent-8.invoke(Unknown Source) ~[?:?]
        at net.kyori.event.method.SimpleMethodSubscriptionAdapter$MethodEventSubscriber.invoke(SimpleMethodSubscriptionAdapter.java:148) ~[velocity.jar:1.1.3]
        at net.kyori.event.SimpleEventBus.post(SimpleEventBus.java:107) ~[velocity.jar:1.1.3]
        at com.velocitypowered.proxy.plugin.VelocityEventManager.fireEvent(VelocityEventManager.java:137) ~[velocity.jar:1.1.3]
        at com.velocitypowered.proxy.plugin.VelocityEventManager.fireShutdownEvent(VelocityEventManager.java:186) ~[velocity.jar:1.1.3]
        at com.velocitypowered.proxy.VelocityServer.lambda$shutdown$2(VelocityServer.java:435) ~[velocity.jar:1.1.3]
        at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by A248** [comment]
Thanks for the report; it should be solved now:
https://github.com/A248/ExecuteEverywhereReloaded/releases/tag/0.1.3
